ARDUINO_DIR = /usr/share/arduino

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS = /usr/share/arduino/hardware/arduino/variants/standard

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

MCU = atmega328

include ./Arduino.mk
